# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931b06d48ee8b2db0a2987a051d40302379594931e3f00889db3972a7ce54dc2639cca0caaa4f2775c41ff9ecd34ad7d104aa1382ca926755e0678ba5efa062d

test:
  secret_key_base: 50e4c23b703d25f5854d3435ccacb36ce13cb5e606380a6e7fc039e37b21301a0a02ef49db6ebb5fcaffce32d2702474514c05e81beec2e3c660ff364b12e3ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
